- name: Deploy SecDevAI-Scanner to AKS
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    image_tag: "{{ image_tag | default('latest') }}"
    acr_name: "{{ acr_name | default('secdevaiacr') }}"
    gemini_api_key: "{{ gemini_api_key | default('') }}"

  tasks:
    - name: Ensure kubernetes.core collection is present
      ansible.builtin.command: ansible-galaxy collection install kubernetes.core
      changed_when: false

    - name: 1. Apply Kubernetes Deployment manifest
      kubernetes.core.k8s:
        state: present
        src: deployment.yml

    - name: 2. Apply Kubernetes Service manifest
      kubernetes.core.k8s:
        state: present
        src: service.yml

    - name: 3. Patch Deployment with new image and env
      kubernetes.core.k8s:
        state: patched
        kind: Deployment
        name: secdevai-app
        namespace: default
        definition:
          spec:
            template:
              spec:
                containers:
                - name: secdevai-container
                  image: "{{ acr_name }}.azurecr.io/secdevai-scanner:{{ image_tag }}"
                  env:
                  - name: GEMINI_API_KEY
                    value: "{{ gemini_api_key }}"
